Abort parser if COMPSEGS is missing for multisegment well.
This might not be 100% perfect but it will detect completely missing
COMPSEGS keywords for multisegment wells already during file parsing
instead of during the simulation at the report step where the problem
occurs (could be rather late). Hence it improves  OPM/opm-simulators#4329.

We keep track of all the wells that appear in WELSEGS and COMPSEGS and
at the end of each report step parsed, we check that there is entry using
COMPSEGS for each well that was in WELSEGS.

Note that the keyword used for the error is the last one in the report
step, which is a bit misleading. Error message looks like:

```
Error: Problem with keyword WCONPROD
In /tmp/MSW-3D-03.DATA line 2462
Missing COMPSEGS keyword for well PROD01 between <memory string> line 0 and /tmp/MSW-3D-03.DATA line 2462.

Error: Unrecoverable errors while loading input: Problem with keyword WCONPROD
In /tmp/MSW-3D-03.DATA line 2462
Missing COMPSEGS keyword for well PROD01 between <memory string> line 0 and /tmp/MSW-3D-03.DATA line 2462.
```