changed: do not prototype boost::filesystem::path
this breaks with g++ 4.8 used in redhat builds.

/usr/include/boost148/boost/filesystem/v3/path.hpp:710:24 error: 'path'
is already declared in this scope.