Provide file and line for errors because of unknown keywords.
```
Error: Unknown keyword: KEY6

Error: Unrecoverable errors while loading input: Problem with keyword
In <memory string> line 0
Unknown keyword: KEY6
```
does not tell the user where his/her error is.

This is now changed to
```
Error: Unknown keyword: KEY6

Error: Unrecoverable errors while loading input: Problem with keyword NE6
In /path/to/include/grid/file.inc line 7
Unknown keyword: KEY6
```
which gives the user a greater chance of finding out what is wrong.