Diagnose Missing Wells/Groups in UDQ DEFINE Statements
This commit adds logic to check if all wells/groups needed in a UDQ
DEFINE statement are present at the point of definition.  In
particular, wells must have been introduced through WELSPECS prior
to the UDQ keyword if any specific well name is used in the defining
expression.  Similarly, well lists must have been introduced and
populated through WLIST before using the well list name in the UDQ.
Finally, groups must be introduced through WELSPECS or GRUPTREE
before using any specific group names in the defining expression.

If this requirement is not met, the parsing process will halt at the
end of reading the full SCHEDULE section in order that all such
problems may be diagnosed in a single run.  Some example output is
shown below.

To this end, make UDQConfig::add_record() return an optional<string>
containing the UDQ name if the record's action is DEFINE, and
nullopt otherwise.  Then the UDQ keyword handler intercepts all new
DEFINE statements and uses UDQDefine::requiredObjects() to identify
any requisite wells or groups.  If any of these are missing, we
issue a diagnostic tagged with the new ParseContext key

    ParseContext::UDQ_DEFINE_CANNOT_EVAL

whose default action is 'DELAYED_EXIT1'.  The default action may be
overridden in the usual way, through environment variables, but
doing so will typically lead to calculating incorrect values for the
user defined quantity.

--------------------------------------------------------------------

Example Output From Missing Well Objects

The message below is printed to OpmLog::error() which will typically
render the text in red colour on the console.

Error: Unrecoverable errors while loading input:

Problem with UDQ
In CASE.DATA line 251
DEFINE cannot be evaluated:
  Missing object in defining expression for FUBHPGI
    -> No existing well matches the name XD-1H