Detect Faulty ACTIONX Summary Vector Names
If an ACTIONX triggering condition does not consist exclusively of
summary vector names, sub-selectors to those, and logical operators,
then we cannot parse it correctly nor emit it to the restart file.
This commit detects a small subset of fault input expressions,
namely those that tries to use arithmetic in place of the summary
vector name.  Proper detection of more invalid inputs will require a
more comprehensive solution, possibly involving rewriting the parser
to use distinct scanning and parsing stages.

For now, this is sufficient to reject conditions of the form

    FUNNY < (FUSK-FULLT)

in which the right-hand side would previously be accepted as the
fallback 'ecl_expr' type.

We now instead emit a diagnostic of the form

  Error: Failed to parse triggering condition for action 'ACT-01':

  Invalid ACTIONX condition right hand side quantity.
  Expected a valid summary vector name, but got '(FUSK-FULLT)' (token[2]).