Emit Usable Diagnostic for Unuspported Restart Report Number
OPM Flow does not support restarting a simulation run from report
step zero.  Previously, this would manifest in a very inscrutable
diagnostic message of the form

    Array ZGRP not found in sequence 0

which, while accurate, does not tell the user what the problem is.

This commit verifies that the restart step supplied as item 2 of the
RESTART keyword is at least one (1).  If not, we now generate a
diagnostic message of the form

    Error: Problem with keyword RESTART
    In CASE.DATA line 1729
    OPM does not support restarting a simulation before report number 1

and stop processing the input file.